INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Teclado Mecânico', 'Switches azuis, ABNT2', 250.00);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Mouse Gamer', '16000 DPI', 180.00);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Monitor 24"', 'IPS Full HD', 799.90);
